### ISSUE TITLE
MVP List 

### ISSUE THREAD

**Issue by PLUCS2** [ShenQi1996/PixelPerfect#1]
- [x] Add a demo user login to auth MVP 
- [x] Remove `following` from the Picture MVP (3rd item) 
- [x] User Profile Page should show the photos that user has uploaded: https://500px.com/p/brun_0?view=photos for example 
- [x] The count of followers a user has (and the number of users they follow) should be displayed on their profile page as part of the `Follows` MVP 

Nice work! I am excited to see your final product!

**Comment by ShenQi1996** [comment]
done
