### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [ShenQi1996/PixelPerfect#2]
- [x] Your Users Table should also have a firstname, lastname, and username column 
- [x] For keywords on the photos table - this should be a BONUS and you will likely want a separate keywords table and a joins table to join photos and keywords 
- [x] Galleries - can a photo belong to multiple galleries? If yes, then there should be a galleries table with a joins table to join photos to galleries (rather than storing a gallery ID on the photos table) 
- [x] Visibility on the galleries table should be renamed to be more semantic (i.e. private or public) 
- [x] You can only like photos (nothing else) - so the likes table columns should be named `liker_id` and `liked_photo_id` the likeable naming convention is specific to polymorphic associations 

Nice work! Let me know if you have any questions

**Comment by ShenQi1996** [comment]
done
