### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by PLUCS2** [ShenQi1996/PixelPerfect#4]
## Backend 
- [x] You should have a route for creating a picture 
- [x] Fix the formatting on follows 
- [x] `return a the gallerie` change to `return a gallery` (Gallery ends in a `y` if it is not plural) 

## Frontend 
- [x] You can look at other users profiles if you are not logged in, so make sure you have accounted for this! 

Nice work! Let me know if you have any questions!

**Comment by ShenQi1996** [comment]
done
